apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      defaultDatabase: btc_analytics
      port: 8123
      server: clickhouse
      username: default
      protocol: http
    secureJsonData:
      password: ""
    isDefault: true
